### ISSUE TITLE
Issue with html2png dependency on selenium-webdriver

### ISSUE THREAD

**Issue by carlpoole** [neonichu/trumpify.js#1]
Was getting this error:

<pre>undefined:1190
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/Users/cpoole/Desktop/trumpify.js/node_modules/html2png/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/Users/cpoole/Desktop/trumpify.js/node_modules/html2png/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /Users/cpoole/Desktop/trumpify.js/node_modules/html2png/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Object.Context.closure.goog.retrieveAndExecModule_ (/Users/cpoole/Desktop/trumpify.js/node_modules/html2png/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/Users/cpoole/Desktop/trumpify.js/node_modules/html2png/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/Users/cpoole/Desktop/trumpify.js/node_modules/html2png/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/Users/cpoole/Desktop/trumpify.js/node_modules/html2png/node_modules/selenium-webdriver/lib/goog/base.js:900:14)</pre>

To fix it I manually replaced the selenium-webdriver folder inside html2png with 

<pre>npm install selenium-webdriver@2.47.0 </pre>

Not sure if a better way to fix, was just hacking around and googled for some way to fix it.

**Comment by talbotseb** [comment]
Thank you !
